name: CI

on:
  workflow_dispatch:

  release:
    # this runs CI only when a release is created at first (and not when it is
    # edited or published)
    types: [created]

  push:
    branches: main

  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3.3.0

    - name: Display CI properties
      run: |
        WD=$(pwd)
        python3 -V
        echo $WD
        clang --version | head -n 1
        echo
        gcc --version | head -n 1
        echo "Github env:"
        env|grep GITHUB
        echo "Android support:"
        env|grep ANDROID

    - name: Install dependencies
      run: |
        sudo apt-get update --fix-missing
        sudo apt-get install -y bash patchelf wget lz4

    - name: Build sdk
      run: |
        chmod +x ./python-*-sdk.sh
        bash -c "./python-wasi-sdk.sh"

    - name: Upload sdk to Github artifacts
      uses: actions/upload-artifact@v3.1.1
      with:
        path: /tmp/sdk

    - name: Upload sdk to Github Releases
      if: github.event_name == 'release'
      uses: svenstaro/upload-release-action@2.3.0
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: /tmp/sdk/*
        file_glob: true
        tag: ${{ github.ref }}
